# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ReduxSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReduxSample
  pod 'ReSwift'

  target 'ReduxSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
